### ISSUE TITLE
Error while filtering/faceting an object with a CustomDataTypeZotero field

### ISSUE THREAD

**Issue by nils-stefan-weiher** [dokempf/easydb-zotero-datatype-plugin#10]
Hi Dominik,

I stumbled upon an error while using the easydb search with an object, containing a field with this custom data type.
Searching with faceting, called Filter in easydb, is not possible and the error returned from the API is a HTTP Status 400 with the following response body:
```
{
    "realm": "api",
    "code": "error.api.invalid_value",
    "parameters": {},
    "description": "Value literature.zotero_reference.conceptName is not valid for field"
}
```

`literature` in this case is the name of the easydb object type containing the Zotero field.
The field itsef is called `zotero_reference`.

Could you look into this?

Tell me if you need any additional information or assistance for this error.

Best wishes,

Nils

**Comment by dokempf** [comment]
I can reproduce this. Unfortunately, I have no idea yet how to fix this. To me, `literature.zotero_reference.conceptName` sounds pretty legit - `conceptName` and `conceptURI` are the two fields in our internal data representations. We inherited this choice from the `CustomDataTypeCommonFacet` base class and changed nothing about it...

**Comment by nils-stefan-weiher** [comment]
Yes, I saw this as well and was baffled. Maybe the search mapping in the manifest.yml is missing?

**Comment by nils-stefan-weiher** [comment]
For example here a mapping for the internal fieldname is specified:
https://github.com/programmfabrik/easydb-custom-data-type-dante/blob/master/manifest.yml#L26-L33C24
easydb uses this to create the Elasticsearch schema from it.

Documentation here:
https://docs.easydb.de/en/technical/plugins/customdatatype/#search-mapping

Its very unclear from the Docs that its needed for search with facets to work and not optional.

EDIT: Add doc link.

**Comment by dokempf** [comment]
Good catch! I will gove this a try tomorrow and let you know.

**Comment by dokempf** [comment]
Indeed, adding the search mapping fixes the API error. I implemented this in #11 and merged it to `main`. However, in my testing, searching did not work the way I expected to. This might be related to some silly wrong usage from my side though. Could you double-check @nils-stefan-weiher ?

**Comment by nils-stefan-weiher** [comment]
Thanks for the quick fix @dokempf !

I will test and let you know.

**Comment by nils-stefan-weiher** [comment]
At the moment filtering and searching seems to work.
I would close this for now and will write, if anything else comes up.
