### ISSUE TITLE
Citation editing is showing HTML source

### ISSUE THREAD

**Issue by nils-stefan-weiher** [dokempf/easydb-zotero-datatype-plugin#12]
Hi Dominik,

in the current version after selecting a citation from the result list the citations is displayed with visible HTML source:

![image](https://github.com/ssciwr/easydb-custom-data-type-zotero/assets/2169369/51b4cd1b-5f7a-4d57-a14e-006a59aca29d)

Could you check where this is coming from?

Thank you again for your great work and best wishes,

Nils

**Comment by dokempf** [comment]
I cannot reproduce this. Maybe the best would be that you show it to me during a video conference? Once I know where it occurs, it should be straight forward to fix - there is a function `__html2text` that is required in some places...

**Comment by nils-stefan-weiher** [comment]
I tried again, this is only displayed like described above during editing of the link. When editing an existing link or entering a new one.

After saving and showing the object containing the field it is shown correctly.

**Comment by dokempf** [comment]
Also while editing, I cannot reproduce. Was this item created a long time ago, maybe with a previous version of the plugin? Does it happen with a freshly created one?

**Comment by nils-stefan-weiher** [comment]
Newly created, using Firefox 113.0.1, easydb version 5.116.0

**Comment by dokempf** [comment]
Could you double check what commit your `easydb-library` submodule points to? It should be `25bd09a`. If it is a different one, you should update the submodule with `git submodule update`.

**Comment by nils-stefan-weiher** [comment]
Oh no ... I am sorry for causing you this much work and annoyance.
Thanks for taking a look.
This actually was the issue, now the citations is showing as intended.

Thank you @dokempf and please forgive me for not properly updating the plugin.

**Comment by dokempf** [comment]
No problem, my research actually exposed another problem: After updating to latest EasyDB, the search filter sidebar also displays HTML:
![Screenshot from 2023-05-23 14-40-33](https://github.com/ssciwr/easydb-custom-data-type-zotero/assets/4989908/d595ed23-d52f-41da-b015-ed780991fc1f)
Do you experience the same?

**Comment by nils-stefan-weiher** [comment]
Yes, I see this as well in our instance.

**Comment by dokempf** [comment]
I fixed this on `main`. When upgrading, make sure to run `npm install` as I had to add a dependency on the server side for the updater to work correctly.

**Comment by nils-stefan-weiher** [comment]
Thanks @dokempf ! Great work as usual. Display of filter is working now.
